### ISSUE TITLE
Support variable bit-width

### ISSUE THREAD

**Issue by ltetzlaff** [sindresorhus/string-hash#1]
I recently encountered a similar use case (went for crc16 btw) where the hash had to be provided as a 16-bit number. Given JS-numbers are 64 bits and [FNV-1a allowing variable bit length up to 1k](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function#Overview) I could see this as a useful configurable parameter defaulting to 64.

What do you think?

**Comment by sindresorhus** [comment]
Sounds useful, but JavaScript only supports up to 53-bit integers. We could use BigInt for this. The package used by this package already supports BigInt, so it's just about finding a good way to expose the capability.

**Comment by sindresorhus** [comment]
Thinking about this more, I think it's better if users just use the `fnv1` package directly if they need `BigInt`.
