### ISSUE TITLE
Re-export?

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/string-hash#4]
Why is this module a re-export of `@sindresorhus/fnv1a`?

I would assume because of the understandable package name.

**Comment by sindresorhus** [comment]
Yes. It's kinda dumb and kinda not. `fnv1a` is not very discoverable if you're looking for a string hash, and I picked the best algorithm here. But `fnv1a` still makes sense as an individual package for discoverability for people looking for the specific algorithm. This also makes it easy to switch out the algorithm if a better one comes along.
