### ISSUE TITLE
Document relation to @sindresorhus/fnv1a

### ISSUE THREAD

**Issue by DanielSWolf** [sindresorhus/string-hash#6]
While looking for a package that generates FNV hashes, I came upon both `@sindresorhus/string-hash` and `@sindresorhus/fnv1a`. I got rather confused trying to find a relevant difference between them, so I fully read through both readme files, then finally the source code itself, where it turned out that this package is merely a one-line wrapper around the other one.

I'm not really sure what the rationale behind this is, but maybe you could add a short sentence to the readme files so that later visitors don't get confused in the same way I did.

**Comment by sindresorhus** [comment]
It's about intent and marketing. When you see "stringHash()" when reading some code, you immediately know what it does. Not so much with "fnv1a()". And most people search for "string hash", not "fnv1a".
